### ISSUE TITLE
failing serve, URI::InvalidURIError

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#43]
```
bundle exec jekyll serve --port 4000 --trace
Configuration file: /home/luke/git/flowcrypt-docs/_config.yml
            Source: /home/luke/git/flowcrypt-docs
       Destination: _site/docs
 Incremental build: disabled. Enable with --incremental
      Generating... 
Traceback (most recent call last):
        37: from /home/luke/git/flowcrypt-docs/vendor/bin/jekyll:23:in `<main>'
        36: from /home/luke/git/flowcrypt-docs/vendor/bin/jekyll:23:in `load'
        35: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/exe/jekyll:15:in `<top (required)>'
        34: from /home/luke/git/flowcrypt-docs/vendor/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        33: from /home/luke/git/flowcrypt-docs/vendor/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        32: from /home/luke/git/flowcrypt-docs/vendor/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        31: from /home/luke/git/flowcrypt-docs/vendor/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        30: from /home/luke/git/flowcrypt-docs/vendor/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        29: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
        28: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/commands/serve.rb:42:in `each'
        27: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
        26: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/commands/build.rb:36:in `process'
        25: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/commands/build.rb:65:in `build'
        24: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/command.rb:28:in `process_site'
        23: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:73:in `process'
        22: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:192:in `render'
        21: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:452:in `render_docs'
        20: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:452:in `each_value'
        19: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:453:in `block in render_docs'
        18: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:453:in `each'
        17: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/site.rb:456:in `block (2 levels) in render_docs'
        16: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/document.rb:348:in `trigger_hooks'
        15: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/hooks.rb:99:in `trigger'
        14: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/hooks.rb:99:in `each'
        13: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-3.6.3/lib/jekyll/hooks.rb:100:in `block in trigger'
        12: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:335:in `block in <top (required)>'
        11: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:35:in `process'
        10: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:65:in `process_html'
         9: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:77:in `process_anchor_tags'
         8: from /home/luke/git/flowcrypt-docs/vendor/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `each'
         7: from /home/luke/git/flowcrypt-docs/vendor/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `upto'
         6: from /home/luke/git/flowcrypt-docs/vendor/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:238:in `block in each'
         5: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
         4: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:92:in `processable_link?'
         3: from /home/luke/git/flowcrypt-docs/vendor/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:196:in `external?'
         2: from /usr/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
         1: from /usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://github.com/FlowCrypt/flowcrypt-backend/pull/95 https://github.com/FlowCrypt/flowcrypt-backend/pull/97 (URI::InvalidURIError)
Makefile:44: recipe for target 'serve' failed
make: *** [serve] Error 1
The terminal process terminated with exit code: 2
```

**Comment by tomholub** [comment]
Please have a look, it seems that it's testing these urls? Which is a good thing, but then we need to see if there is a way to mark them as internal

**Comment by seisvelas** [comment]
The problem was that I had misformatted a markdown link. In fixed-vulnerabilities.md I wrote:

    [https://github.com/FlowCrypt/flowcrypt-backend/pull/97](https://github.com/FlowCrypt/flowcrypt-backend/pull/95 https://github.com/FlowCrypt/flowcrypt-backend/pull/97)

When I should have written:

    [https://github.com/FlowCrypt/flowcrypt-backend/pull/97](https://github.com/FlowCrypt/flowcrypt-backend/pull/97)

I tried it after fixing the link and it works. I need to update that page anyway with some new content. I'll make a PR later today.
